---
title: "Data wrangling with the {tidyverse}"
format: html
editor: visual
---

## Week 1 Discussion: Exercise

### Data wrangling with the `{tidyverse}`

##### Thursday January 8^th^, 2026

#### Load library

```{r}
library(janitor)
library(tidyverse)
library(ggplot2)
```

### Import Data

```{r}
stressor <- read_csv(here::here("data", "week1data", "stressor.csv")) %>% 
  clean_names()
```
### Basic Data Exploration

```{r}
# Check class of year variable
lapply(stressor, class)
```

```{r}
names(stressor)
```

```{r}
summary(stressor)
```

### Clean Data

```{r}
# Remove all special characters in the state and stressor columns
stressor_clean <- stressor %>% 
  clean_names() %>%
  mutate(state = str_remove_all(state, "[^a-zA-Z ]"),
         stressor = str_remove_all(stressor, "[^a-zA-Z ]")) %>%
  # Convert year variable from string to numeric
  mutate(year = as.numeric(year)) 
```

### Change dataframe

```{r}
# Pivot the data frame to look it tidy

# Convert data frame from wide to longer
stressor_clean_df <- stressor_clean %>% 
  pivot_longer(cols = c("january_march",
                        "april_june",
                        "july_september",
                        "october_december"),
               names_to = "months",
               values_to = "stress_pct") %>%
  # Convert months to quarter number-- 
  mutate(quarter = case_when(
    months == "january_march" ~ 1,
    months == "april_june" ~ 2, 
    months == "july_september" ~ 3, 
    months == "october_december" ~ 4)) %>% 
  # Remove "United States" and "Other States" observations
  filter(state != "United States", state != "Other States") %>% 
  # Select a specific stressor
  filter(stressor == "Pesticides") %>% 
  # Select a specific state 
  filter(state == "California") %>% 
  # Calculate quarterly average for each year --
  group_by(year, quarter) %>% 
  summarise(avg_stress_pct = mean(stress_pct, na.rm = TRUE))
```

### Data Visualization

```{r}
stressor_clean_df |>
  ggplot(aes(x = quarter, y = avg_stress_pct, color = factor(year))) +
  geom_line(linewidth = 1) +
  geom_point(size = 3) +
  scale_color_brewer(palette = "Accent")+
  scale_x_continuous(breaks = 1:4, labels = c("Q1", "Q2", "Q3", "Q4")) +
  scale_y_continuous(labels = scales::label_number(suffix = "%")) +
  labs(
    title = "Pesticide Stress on California Bee Colonies",
    subtitle = "Quarterly averages across years",
    x = "Quarter",
    y = "Average Percent of Bee Colonies Affected",
    color = "Year"
  ) +
  theme_minimal()

```
