---
title: "Writing Alt Text"
author: "Aakriti Poudel"
format: html
editor: visual
---

## Week 2 Lab: Exercise
**Writing Alt Text**
January 15th, 2026

## Setup:
Find a partner and decide who will be Partner 1 and Partner 2.

If you are Partner #1, copy the Partner #1 code chunk below into your qmd. If you are Partner #2, copy the Partner #2 code chunk below into your qmd.

## PARTNER 1

```{r}
library(ggplot2)
library(tidyverse)
library(palmerpenguins)

ggplot(data = penguins, aes(x = body_mass_g, fill = species)) +
  geom_histogram(alpha = 0.5, 
                 position = "identity") +
  scale_fill_manual(values = c("darkorange","purple","cyan4")) +
  labs(x = "Body mass (g)",
       y = "Frequency",
       title = "Penguin body masses")
```
## PARTNER 2

```{r}
#install.packages("lterdatasampler")
library(lterdatasampler)
library(tidyr)
library(ggplot2)

pie_crab %>%

  ggplot(aes(y=latitude, x = size, group = latitude)) +

  geom_boxplot() +

  scale_x_continuous(breaks = seq(from = 7, to = 23, by = 2), limits = c(6.5,24))+

  scale_y_continuous(breaks = seq(from = 29, to = 43, by = 2), limits = c(29, 43.5)) +

  labs(title = "Crab carapace size (mm) by latitude")
```

